# Generated by Django 4.0.4 on 2022-04-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('latitude', models.CharField(max_length=13, verbose_name='Latitude')),
                ('data_expiracao', models.DateField(verbose_name='Data de expiração')),
            ],
        ),
    ]
