# Generated by Django 4.0.4 on 2022-05-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='longitude',
            field=models.FloatField(default=1, max_length=25, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campo',
            name='latitude',
            field=models.FloatField(max_length=25, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
    ]
